<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Manager - List </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Contact Manager</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/contacts">List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/contacts/add">Add Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/contacts/export">Export Contacts to CSV</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/logout">Logout</a>
                    </li>
                </ul>
                <form class="d-flex" action="/contacts"> <!-- inserir o paramento "action", para utilizar o butão Search -->
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <main class="container mt-4">
        <?php if (isset($message)): ?>
            <div class="alert alert-info">
                <?= $message ?>
            </div>
        <?php endif; ?>

        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Contact</th>
                    <th></th>
                </tr>
            </thead>
            <tbody> 
               <?php if (count($contacts) > 0) : ?> 
                    <?php foreach ($contacts as $contact) : ?> <!-- mostrar contatos -->
                        <tr> 
                           <td><?= $contact->id ?></td>
                           <td><?= $contact->name ?></td>
                           <td><?= $contact->email ?></td>
                           <td>
                               <a href="/contacts/update?id=<?= $contact->id ?>">Edit</a> <!-- Trago parametro GET p?id -->
                               <a href="/contacts/remove?id=<?= $contact->id ?>">Remove</a>
                           </td>
                       </tr> 
                    <?php endforeach; ?> 
               <?php  else : ?>
                      <tr>
                          <td colspan="4">No contacts</td>
                      </tr>
               <?php endif; ?> 

            </tbody>
        </table>
    </main>    
</body>
</html>