<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Manager - Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="./styles/signin.css">
</head>

<body class="text-center">
    
    <main class="form-signin">
        <form method="post">
            <?php if (isset($message)) : ?>
                <div class="alert alert-danger">
                    <?= $message ?>
                </div>
            <?php endif; ?>

            <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

            <div class="form-floating">
                <input type="text" class="form-control" id="usernameInput" placeholder="username" name="username">
                <label for="usernameInput">Username</label>
            </div>
            <div class="form-floating">
                <input type="password" class="form-control" id="passwordInput" placeholder="Password" name="password">
                <label for="passwordInput">Password</label>
            </div>

            <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
            <a href="/signup">Sign Up</a>

        </form>
    </main>
  </body>
</html>